/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getPollSystemAccess().getGroup(), "rule__PollSystem__Group__0");
			builder.put(grammarAccess.getPollSystemAccess().getGroup_3(), "rule__PollSystem__Group_3__0");
			builder.put(grammarAccess.getPollAccess().getGroup(), "rule__Poll__Group__0");
			builder.put(grammarAccess.getPollAccess().getGroup_4(), "rule__Poll__Group_4__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup(), "rule__Question__Group__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup_3(), "rule__Question__Group_3__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup_4(), "rule__Question__Group_4__0");
			builder.put(grammarAccess.getOptionAccess().getGroup(), "rule__Option__Group__0");
			builder.put(grammarAccess.getOptionAccess().getGroup_3(), "rule__Option__Group_3__0");
			builder.put(grammarAccess.getOptionAccess().getGroup_4(), "rule__Option__Group_4__0");
			builder.put(grammarAccess.getPollSystemAccess().getPollsAssignment_3_1(), "rule__PollSystem__PollsAssignment_3_1");
			builder.put(grammarAccess.getPollAccess().getNameAssignment_2(), "rule__Poll__NameAssignment_2");
			builder.put(grammarAccess.getPollAccess().getQuestionsAssignment_4_1(), "rule__Poll__QuestionsAssignment_4_1");
			builder.put(grammarAccess.getQuestionAccess().getTextAssignment_3_1(), "rule__Question__TextAssignment_3_1");
			builder.put(grammarAccess.getQuestionAccess().getOptionsAssignment_4_1(), "rule__Question__OptionsAssignment_4_1");
			builder.put(grammarAccess.getOptionAccess().getIdAssignment_3_1(), "rule__Option__IdAssignment_3_1");
			builder.put(grammarAccess.getOptionAccess().getTextAssignment_4_1(), "rule__Option__TextAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
