/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import questionnaireModel.Poll;
import questionnaireModel.PollSystem;
import questionnaireModel.Question;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final PollSystem pollSystem, @Extension final IFormattableDocument document) {
    document.<Poll>format(pollSystem.getPolls());
  }
  
  protected void _format(final Poll poll, @Extension final IFormattableDocument document) {
    document.<Question>format(poll.getQuestions());
  }
  
  public void format(final Object poll, final IFormattableDocument document) {
    if (poll instanceof XtextResource) {
      _format((XtextResource)poll, document);
      return;
    } else if (poll instanceof Poll) {
      _format((Poll)poll, document);
      return;
    } else if (poll instanceof PollSystem) {
      _format((PollSystem)poll, document);
      return;
    } else if (poll instanceof EObject) {
      _format((EObject)poll, document);
      return;
    } else if (poll == null) {
      _format((Void)null, document);
      return;
    } else if (poll != null) {
      _format(poll, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(poll, document).toString());
    }
  }
}
